@startuml
left to right direction

frame "uc Guest" {
  actor "Guest" as g
  
  rectangle " " {
    usecase "Đăng nhập" as UC1
    usecase "Đăng ký" as UC2
    usecase "Quên mật khẩu" as UC3
  }
}

g -- UC1
g -- UC2
g -- UC3
@enduml
