@startuml
left to right direction
skinparam packageStyle rectangle
skinparam actorStyle awesome

actor "User" as Guest

package "Backend API (NodeJS & ExpressJS)" {
    usecase "Đăng nhập hệ thống\n(Auth Controller)" as UC_Login
    usecase "Xác thực dữ liệu đầu vào\n(Express Validation Middleware)" as UC_Validate
    usecase "Chống Brute-force/Spam\n(Express Rate Limiting Middleware)" as UC_RateLimit
    usecase "Truy xuất Email & Trạng thái\n(MongoDB & Mongoose)" as UC_CheckUser
    usecase "Kiểm tra Mật khẩu (Bcrypt)\n(Auth Service)" as UC_CheckPass
    usecase "Khởi tạo JSON Web Token (JWT)\n(Auth Service)" as UC_GenerateJWT
    usecase "Phân quyền (Role-based)\n(User/Admin)" as UC_Authorize
}

Guest --> UC_Login

UC_Login ..> UC_RateLimit : <<include>>
UC_Login ..> UC_Validate : <<include>>
UC_Login ..> UC_CheckUser : <<include>>
UC_Login ..> UC_CheckPass : <<include>>
UC_Login ..> UC_GenerateJWT : <<include>>
UC_Login ..> UC_Authorize : <<include>>

@enduml
