@startuml
left to right direction
skinparam packageStyle rectangle

actor "User" as User
actor "Admin" as Admin

package "Quản lý Hồ sơ" {
  usecase "Chỉnh sửa hồ sơ (Edit Profile)" as UC_Edit
}

User --> UC_Edit
Admin --> UC_Edit



@enduml